### ISSUE TITLE
build: 3.14.1 fails to build on Fedora 44 with gcc 16.0.1

### ISSUE THREAD

**Issue by ycollet** [supercollider/supercollider#7412]
## Environment

* SuperCollider version: 3.14.1
* Operating system: Fedora 44
* Boost version:

## Description

I am trying to build supercollider on Fedora 44 with gccv 16.0.1. I met the following error message:
```
/builddir/build/BUILD/supercollider-3.14.1-build/SuperCollider-3.14.1-Source/editors/sc-ide/widgets/code_editor/editor.cpp:701:46: error: no matching function for call to ‘QString::arg(Qt::KeyboardModifiers)’
  701 |                                          .arg(e->modifiers())
      |                                              ^
  • there are 4 candidates
    • candidate 1: ‘template<class T, typename std::enable_if<conjunction_v<std::disjunction<std::is_integral<_Tp>, std::conjunction<std::is_enum<_Tp>, std::negation<q23::is_scoped_enum<E, is_enum_v<E> > > > >, std::negation<std::disjunction<std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, _Float16>, std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, qfloat16>, std::is_floating_point<_Tp> > >, std::negation<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv< <template-parameter-1-1> >::type> >, std::is_convertible<T, QAnyStringView> > > >, bool>::type <anonymous> > QString QString::arg(T, int, int, QChar) const’
      /usr/include/qt6/QtCore/qstring.h:324:27:
        324 |     [[nodiscard]] QString arg(T a, int fieldWidth = 0, int base = 10,
            |                           ^~~
      • template argument deduction/substitution failed:
        • error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
          /usr/include/qt6/QtCore/qstring.h:323:53:
            323 |     template <typename T, if_integral_non_char<T> = true>
                |                                                     ^~~~
    • candidate 2: ‘template<class T, typename std::enable_if<std::disjunction<std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, _Float16>, std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, qfloat16>, std::is_floating_point<_Tp> >::value, bool>::type <anonymous> > QString QString::arg(T, int, char, int, QChar) const’
      /usr/include/qt6/QtCore/qstring.h:339:27:
        339 |     [[nodiscard]] QString arg(T a, int fieldWidth = 0, char format = 'g', int precision = -1,
            |                           ^~~
      • template argument deduction/substitution failed:
        • error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
          /usr/include/qt6/QtCore/qstring.h:338:50:
            338 |     template <typename T, if_floating_point<T> = true>
                |                                                  ^~~~
    • candidate 3: ‘template<class T, typename std::enable_if<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv< <template-parameter-1-1> >::type> >, std::is_convertible<T, QAnyStringView> >::value, bool>::type <anonymous> > QString QString::arg(const T&, int, QChar) const’
      /usr/include/qt6/QtCore/qstring.h:344:27:
        344 |     [[nodiscard]] QString arg(const T &a, int fieldWidth = 0, QChar fillChar = u' ') const
            |                           ^~~
      • template argument deduction/substitution failed:
        • error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
          /usr/include/qt6/QtCore/qstring.h:343:47:
            343 |     template <typename T, if_string_like<T> = true>
                |                                               ^~~~
    • candidate 4: ‘template<class ... Args> typename std::enable_if<((sizeof... (Args) >= 2) && conjunction_v<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv<Args>::type> >, std::is_convertible<Args, QAnyStringView> >...>), QString>::type QString::arg(Args&& ...) const’
      /usr/include/qt6/QtCore/qstring.h:364:5:
        364 |     arg(Args &&...args) const
            |     ^~~
      • template argument deduction/substitution failed:
        • /usr/include/qt6/QtCore/qstring.h: In substitution of ‘template<class ... Args> typename std::enable_if<((sizeof... (Args) >= 2) && conjunction_v<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv<Args>::type> >, std::is_convertible<Args, QAnyStringView> >...>), QString>::type QString::arg(Args&& ...) const [with Args = {QFlags<Qt::KeyboardModifier>}]’:
        • required from here
          /builddir/build/BUILD/supercollider-3.14.1-build/SuperCollider-3.14.1-Source/editors/sc-ide/widgets/code_editor/editor.cpp:701:46:   
            701 |                                          .arg(e->modifiers())
                |                                              ^
        • error: no type named ‘type’ in ‘struct std::enable_if<false, QString>’
          /usr/include/qt6/QtCore/qstring.h:364:5:
            364 |     arg(Args &&...args) const
                |     ^~~
/builddir/build/BUILD/supercollider-3.14.1-build/SuperCollider-3.14.1-Source/editors/sc-ide/widgets/code_editor/editor.cpp: In member function ‘virtual void ScIDE::GenericCodeEditor::mouseDoubleClickEvent(QMouseEvent*)’:
/builddir/build/BUILD/supercollider-3.14.1-build/SuperCollider-3.14.1-Source/editors/sc-ide/widgets/code_editor/editor.cpp:735:46: error: no matching function for call to ‘QString::arg(Qt::KeyboardModifiers)’
  735 |                                          .arg(e->modifiers())
      |                                              ^
  • there are 4 candidates
    • candidate 1: ‘template<class T, typename std::enable_if<conjunction_v<std::disjunction<std::is_integral<_Tp>, std::conjunction<std::is_enum<_Tp>, std::negation<q23::is_scoped_enum<E, is_enum_v<E> > > > >, std::negation<std::disjunction<std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, _Float16>, std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, qfloat16>, std::is_floating_point<_Tp> > >, std::negation<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv< <template-parameter-1-1> >::type> >, std::is_convertible<T, QAnyStringView> > > >, bool>::type <anonymous> > QString QString::arg(T, int, int, QChar) const’
      /usr/include/qt6/QtCore/qstring.h:324:27:
        324 |     [[nodiscard]] QString arg(T a, int fieldWidth = 0, int base = 10,
            |                           ^~~
      • template argument deduction/substitution failed:
        • error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
          /usr/include/qt6/QtCore/qstring.h:323:53:
            323 |     template <typename T, if_integral_non_char<T> = true>
                |                                                     ^~~~
    • candidate 2: ‘template<class T, typename std::enable_if<std::disjunction<std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, _Float16>, std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, qfloat16>, std::is_floating_point<_Tp> >::value, bool>::type <anonymous> > QString QString::arg(T, int, char, int, QChar) const’
      /usr/include/qt6/QtCore/qstring.h:339:27:
        339 |     [[nodiscard]] QString arg(T a, int fieldWidth = 0, char format = 'g', int precision = -1,
            |                           ^~~
      • template argument deduction/substitution failed:
        • error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
          /usr/include/qt6/QtCore/qstring.h:338:50:
            338 |     template <typename T, if_floating_point<T> = true>
                |                                                  ^~~~
    • candidate 3: ‘template<class T, typename std::enable_if<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv< <template-parameter-1-1> >::type> >, std::is_convertible<T, QAnyStringView> >::value, bool>::type <anonymous> > QString QString::arg(const T&, int, QChar) const’
      /usr/include/qt6/QtCore/qstring.h:344:27:
        344 |     [[nodiscard]] QString arg(const T &a, int fieldWidth = 0, QChar fillChar = u' ') const
            |                           ^~~
      • template argument deduction/substitution failed:
        • error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
          /usr/include/qt6/QtCore/qstring.h:343:47:
            343 |     template <typename T, if_string_like<T> = true>
                |                                               ^~~~
    • candidate 4: ‘template<class ... Args> typename std::enable_if<((sizeof... (Args) >= 2) && conjunction_v<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv<Args>::type> >, std::is_convertible<Args, QAnyStringView> >...>), QString>::type QString::arg(Args&& ...) const’
      /usr/include/qt6/QtCore/qstring.h:364:5:
        364 |     arg(Args &&...args) const
            |     ^~~
      • template argument deduction/substitution failed:
        • /usr/include/qt6/QtCore/qstring.h: In substitution of ‘template<class ... Args> typename std::enable_if<((sizeof... (Args) >= 2) && conjunction_v<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv<Args>::type> >, std::is_convertible<Args, QAnyStringView> >...>), QString>::type QString::arg(Args&& ...) const [with Args = {QFlags<Qt::KeyboardModifier>}]’:
        • required from here
          /builddir/build/BUILD/supercollider-3.14.1-build/SuperCollider-3.14.1-Source/editors/sc-ide/widgets/code_editor/editor.cpp:735:46:   
            735 |                                          .arg(e->modifiers())
                |                                              ^
        • error: no type named ‘type’ in ‘struct std::enable_if<false, QString>’
          /usr/include/qt6/QtCore/qstring.h:364:5:
            364 |     arg(Args &&...args) const
                |     ^~~
/builddir/build/BUILD/supercollider-3.14.1-build/SuperCollider-3.14.1-Source/editors/sc-ide/widgets/code_editor/editor.cpp: In member function ‘virtual void ScIDE::GenericCodeEditor::mouseReleaseEvent(QMouseEvent*)’:
/builddir/build/BUILD/supercollider-3.14.1-build/SuperCollider-3.14.1-Source/editors/sc-ide/widgets/code_editor/editor.cpp:769:46: error: no matching function for call to ‘QString::arg(Qt::KeyboardModifiers)’
  769 |                                          .arg(e->modifiers())
      |                                              ^
  • there are 4 candidates
    • candidate 1: ‘template<class T, typename std::enable_if<conjunction_v<std::disjunction<std::is_integral<_Tp>, std::conjunction<std::is_enum<_Tp>, std::negation<q23::is_scoped_enum<E, is_enum_v<E> > > > >, std::negation<std::disjunction<std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, _Float16>, std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, qfloat16>, std::is_floating_point<_Tp> > >, std::negation<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv< <template-parameter-1-1> >::type> >, std::is_convertible<T, QAnyStringView> > > >, bool>::type <anonymous> > QString QString::arg(T, int, int, QChar) const’
      /usr/include/qt6/QtCore/qstring.h:324:27:
        324 |     [[nodiscard]] QString arg(T a, int fieldWidth = 0, int base = 10,
            |                           ^~~
      • template argument deduction/substitution failed:
        • error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
          /usr/include/qt6/QtCore/qstring.h:323:53:
            323 |     template <typename T, if_integral_non_char<T> = true>
                |                                                     ^~~~
    • candidate 2: ‘template<class T, typename std::enable_if<std::disjunction<std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, _Float16>, std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, qfloat16>, std::is_floating_point<_Tp> >::value, bool>::type <anonymous> > QString QString::arg(T, int, char, int, QChar) const’
      /usr/include/qt6/QtCore/qstring.h:339:27:
        339 |     [[nodiscard]] QString arg(T a, int fieldWidth = 0, char format = 'g', int precision = -1,
            |                           ^~~
      • template argument deduction/substitution failed:
        • error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
          /usr/include/qt6/QtCore/qstring.h:338:50:
            338 |     template <typename T, if_floating_point<T> = true>
                |                                                  ^~~~
    • candidate 3: ‘template<class T, typename std::enable_if<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv< <template-parameter-1-1> >::type> >, std::is_convertible<T, QAnyStringView> >::value, bool>::type <anonymous> > QString QString::arg(const T&, int, QChar) const’
      /usr/include/qt6/QtCore/qstring.h:344:27:
        344 |     [[nodiscard]] QString arg(const T &a, int fieldWidth = 0, QChar fillChar = u' ') const
            |                           ^~~
      • template argument deduction/substitution failed:
        • error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
          /usr/include/qt6/QtCore/qstring.h:343:47:
            343 |     template <typename T, if_string_like<T> = true>
                |                                               ^~~~
    • candidate 4: ‘template<class ... Args> typename std::enable_if<((sizeof... (Args) >= 2) && conjunction_v<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv<Args>::type> >, std::is_convertible<Args, QAnyStringView> >...>), QString>::type QString::arg(Args&& ...) const’
      /usr/include/qt6/QtCore/qstring.h:364:5:
        364 |     arg(Args &&...args) const
            |     ^~~
      • template argument deduction/substitution failed:
        • /usr/include/qt6/QtCore/qstring.h: In substitution of ‘template<class ... Args> typename std::enable_if<((sizeof... (Args) >= 2) && conjunction_v<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv<Args>::type> >, std::is_convertible<Args, QAnyStringView> >...>), QString>::type QString::arg(Args&& ...) const [with Args = {QFlags<Qt::KeyboardModifier>}]’:
        • required from here
          /builddir/build/BUILD/supercollider-3.14.1-build/SuperCollider-3.14.1-Source/editors/sc-ide/widgets/code_editor/editor.cpp:769:46:   
            769 |                                          .arg(e->modifiers())
                |                                              ^
        • error: no type named ‘type’ in ‘struct std::enable_if<false, QString>’
          /usr/include/qt6/QtCore/qstring.h:364:5:
            364 |     arg(Args &&...args) const
                |     ^~~
```

**Comment by capital-G** [comment]
Thanks for the report - can you state which Qt version you are using?
Additionally, can you check if the development branch works for you?

**Comment by ycollet** [comment]
The version used on Fedora 44 is 6.10.2.

**Comment by capital-G** [comment]
Thanks - this should be a duplicate of https://github.com/supercollider/supercollider/issues/7279 and has been fixed on dev via https://github.com/supercollider/supercollider/pull/7290

Can you try out if it works for you on the development branch?

**Comment by ycollet** [comment]
Tested and the build went fine on Fedora 44. So, this bug can be closed ...
