### ISSUE TITLE
Library fails to compile fully after boost CLI changes

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#6764]
## Environment

* SuperCollider version: Commit ID 06aaa4da or later
* Operating system: n/a
* Other details (Qt version, audio driver, etc.): n/a

## Steps to reproduce

```supercollider
$ sclang
compiling class library...
	Found 882 primitives.
ERROR: There is a discrepancy.
numClassDeps 0   gNumClasses 82
ERROR: Library has not been compiled successfully.
cleaning up OSC
```

## Expected vs. actual behavior

Commit 06aaa4da was found by git bisect.

If I go to the commit immediately before 06aaa4da, then sclang starts and runs normally.

I *think* the issue is that some locations (perhaps all locations) under Extensions are not being compiled. My startup.scd file contains references to at least one class defined under Extensions, and in the broken situation, if I open the IDE, I see compilation errors in the startup file specifically for that class (but the class is found in the working commit, without changing anything in the configuration).

Actually, I can confirm that -- if I explicitly add `/home/xxx/.local/share/SuperCollider/Extensions` to includePaths in sclang_conf.yaml, then the bad commit starts correctly.

So apparently, something in the bad commit removes Extensions from the list of default locations.

**Comment by capital-G** [comment]
Thanks for the report james, I thought I tested it properly but I may have missed something, I'll take a look at this tomorrow.

**Comment by dyfer** [comment]
Thanks for reporting.
Just to add to the confusion, the boost CLI changes seemed to have _fixed_ a very similar behavior I observed _on Windows_, see #6743. @jamshark70 what platform is this on?

**Comment by dyfer** [comment]
Also, keep in mind that this does **not** break SC on every platform. In particular, the testsuite still runs on macOS and Linux after the changes to boost CLI. This behavior is likely triggered by a combination of factors.

**Comment by elgiano** [comment]
I think testsuite works because it executes a file. On my system (arch linux) I can run a .scd file but not go in interactive mode.

I'm trying without config file or with a default config file generated by scide:
```yaml
includePaths:
    []
excludePaths:
    []
postInlineWarnings: false
excludeDefaultPaths: false
```
I get this output, in both cases, and then it hangs forever
```
compiling class library...
	Found 873 primitives.
	Compiling directory '/usr/share/SuperCollider/SCClassLibrary'
	Compiling directory '/usr/share/SuperCollider/Extensions'
	Compiling directory '/home/[redacted]/.local/share/SuperCollider/Extensions'
	numentries = 1480202 / 26341056 = 0.056
	6768 method selectors, 3892 classes
	method table size 25214720 bytes, big table size 210728448
	Number of Symbols 17832
	Byte Code Size 552869
	compiled 745 files in 0.76 seconds

Info: 7 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.02 seconds


*** Welcome to SuperCollider 3.14.0-dev. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim).
```
scide without config file gets me the same output as James

**Comment by jamshark70** [comment]
> what platform is this on?

I'm on Linux.

> Also, keep in mind that the listed commit did not break SC on every platform in default configuration. ... This behavior is likely triggered by a combination of factors.

I thought so. I haven't been able to guess what the combination of factors could be, in my case.

**Comment by jamshark70** [comment]
Also -- like elgiano, the behavior on my system depends on the configuration file used.

For me:

- Command line, no config file: As above ("discrepancy" and immediate exit).
- Command line and IDE both, with config file: sclang compiles the library (though in my case, without Extensions) and executes startup behaviors, and then will not respond to interactive code submission.

My sclang configuration includes this, along with a whole bunch of quarks:

```
includePaths:
    -   /home/xxx/share/superc-dev/SCClassLibrary
excludePaths:
    -   /usr/local/share/SuperCollider/SCClassLibrary
```

I note that elgiano, with empty include/exclude paths, does get the default class library and extension directories. I guess the most likely explanation is that the presence of include/exclude paths causes Extensions to get dropped. (Or perhaps the new logic somewhere sees that I've disabled the default class library location, and then disables extensions as well? That would be odd, though, for something so specific to occur accidentally.)

So wrt dyfer's comment -- "testsuite still runs in CI on macOS and Linux after the changes to boost CLI" -- does the config file in CI specify any include/exclude paths? If it doesn't, then CI might simply be sidestepping the bug.

**Comment by dyfer** [comment]
> does the config file in CI specify any include/exclude paths?

Well, yes. The path with the testsuite. The mechanism currently is:
1. add path: run sclang with [add_include_path.scd](https://github.com/supercollider/supercollider/blob/develop/testsuite/scripts/add_include_path.scd) - this adds the testsuite path to the current config file
2. run tests: sclang with [sclang_test_runner.scd](https://github.com/supercollider/supercollider/blob/develop/testsuite/scripts/sclang_test_runner.scd)
3. print results: sclang with [print_results.scd](https://github.com/supercollider/supercollider/blob/develop/testsuite/scripts/print_results.scd)

You can see this in the [CI config file](https://github.com/supercollider/supercollider/blob/develop/.github/workflows/test_linux.yml#L58-L70).

Here's a branch that runs and includes the offending commit, for reference: https://github.com/dyfer/supercollider/commits/refs/heads/windowsTests-rebased/
Tests do run on all 3 platforms here (some tests fail though).

**Comment by dyfer** [comment]
On macOS I tried starting sclang with and without config file; I also tried starting IDE with and without the config file and I couldn't reproduce the issue.

@elgiano @jamshark70 does the issue occur with an empty `startup.scd` as well?

**Comment by elgiano** [comment]
I think I've found the issue, or at least one issue.  SC_LanguageClient::Options needs to be initialized.
Comments below are mine:

lang/LangSource/SC_TerminalClient.h:
```cpp
     struct Options : public SC_LanguageClient::Options {
+        // no default constructors, fields can be garbage
         std::string mLibraryConfigFile;
         bool mDaemon;
         bool mCallRun;
```

lang/LangSource/SC_CLIOptions.cpp b/lang/LangSource/SC_CLIOptions.cpp:
```cpp
@@ -116,6 +116,7 @@ po::options_description CLIOptions::buildTerminalDescription(SC_TerminalClient::
         )
         (
             "daemon,D",
+           // here defaults values access the uninitialized terminalOptions fields
             po::bool_switch(&terminalOptions.mDaemon)->default_value(terminalOptions.mDaemon),
             "Enter daemon mode"
         )
```
lang/LangSource/SC_TerminalClient.cpp b/lang/LangSource/SC_TerminalClient.cpp:
```cpp
 int SC_TerminalClient::run(int argc, char** argv) {
+   // here mOptions should be initialized
     Options& opt = mOptions;

     SC_CLI::CLIOptions cliOptions;

```

```cpp
@@ -138,11 +139,14 @@ int SC_TerminalClient::run(int argc, char** argv) {
     if (opt.mCallRun)
         runMain();

     // here mDaemon defaults to 80 instead of to 0
     if (opt.mDaemon) {
         daemonLoop();
     } else {
         initInput();
         startInput();
```

so in the end it never enters interactive mode.

I'm not sure it would be the best fix, but initializing all bool struct members to 0 would fix it.

```diff
diff --git a/lang/LangSource/SC_TerminalClient.h b/lang/LangSource/SC_TerminalClient.h
index 38696ae5f..60f7131b3 100644
--- a/lang/LangSource/SC_TerminalClient.h
+++ b/lang/LangSource/SC_TerminalClient.h
@@ -56,10 +56,10 @@ public:

     struct Options : public SC_LanguageClient::Options {
         std::string mLibraryConfigFile;
-        bool mDaemon;
-        bool mCallRun;
-        bool mCallStop;
-        bool mStandalone;
+        bool mDaemon = 0;
+        bool mCallRun = 0;
+        bool mCallStop = 0;
+        bool mStandalone = 0;
         std::vector<std::string> mArgs;
     };
```
