### ISSUE TITLE
command line sclang requires macOS 11 despite otherwise being 10.14 compatible (because of readline)

### ISSUE THREAD

**Issue by ahihi** [supercollider/supercollider#6376]
## Environment

* SuperCollider version: 3.13.0
* Operating system: macOS 10.14

## Steps to reproduce

run the `sclang` executable in a terminal (interactively) and type any character.

## Expected vs. actual behavior

it crashes with

```
sc3> dyld: lazy symbol binding failed: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/../Frameworks/libreadline.8.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/../Frameworks/libreadline.8.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

maybe just a side effect of how readline was built on the CI machine?

**Comment by dyfer** [comment]
Thanks for the report.

> maybe just a side effect of how readline was built on the CI machine?

Yes, certainly. 

This is for the regular "universal" 3.13 release build, right?

I'm guessing that using the legacy build would work, can you check?

**Comment by ahihi** [comment]
> This is for the regular "universal" 3.13 release build, right?

yeah.

> I'm guessing that using the legacy build would work, can you check?

seems so! is there any disadvantage to using this build on 10.14?

**Comment by dyfer** [comment]
> seems so! is there any disadvantage to using this build on 10.14?

The legacy build It comes bundled with older Qt libraries. There might be slight differences in the GUI drawing and look&feel. In case you'd use the helpbrowser / webview to access online resources, the bundled web browser is older so there might be security considerations there... but this is purely theoretical.

There should be no difference in capabilities and performance.

**Comment by dyfer** [comment]
As of October 2024 even the legacy build doesn't support macOS 10.14, unfortunately.
The release SC 3.13 legacy does support macOS 10.14.
