### PR TITLE
supernova: fix include w/ system boost

### PR DESCRIPTION
**Pull request by tharvik**
## Purpose and Motivation

when compiling w/ system boost (1.88.0) and w/o jack, it fails with
```
SuperCollider-3.14.0-Source/server/supernova/server/server.cpp:278:16: error: ‘tie’ is not a member of ‘boost’; did you mean ‘xtime’?
  278 |         boost::tie(min, max) = thread_priority_interval_rt();
      |                ^~~
      |                xtime
```

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks @tharvik 
FWIW at least on macOS we build with system boost 1.89 and I haven't seen that issue.
Also, coincidentally I have just been [working on cleaning up boost cmake integration](https://github.com/supercollider/supercollider/pull/7116) and I wonder if it changes anything. Could you test https://github.com/supercollider/supercollider/tree/topic-boost-cmake on your system?

**Comment by tharvik** [comment]
> FWIW at least on macOS we build with system boost 1.89 and I haven't seen that issue.

hum, maybe it's the combination of cmake flags I'm using? I can paste some more info if you want to look more into it.

> Also, coincidentally I have just been [working on cleaning up boost cmake integration](https://github.com/supercollider/supercollider/pull/7116) and I wonder if it changes anything. Could you test https://github.com/supercollider/supercollider/tree/topic-boost-cmake on your system?

haa, yes, I saw it too, and hoped that it would fix my build but to no avail.

**Comment by dyfer** [comment]
> hum, maybe it's the combination of cmake flags I'm using? I can paste some more info if you want to look more into it.

Could you please file this as an issue, instead of pasting here? Include system details, as well as cmake invocation and full output of the configure step (in addition to the error, of course).

Thanks!

**Comment by dyfer** [comment]
I think we should actually modernize the use of tuples (which will remove boost dependency here). Can you try https://github.com/supercollider/supercollider/tree/topic/cpp-structured-bindings ?

**Comment by dyfer** [comment]
@tharvik if you confirm that the linked branch (which is the base for #7119) fixes this, I'd suggest that this PR is closed and superseded by 7119.

**Comment by tharvik** [comment]
> Could you please file this as an issue, instead of pasting here? Include system details, as well as cmake invocation and full output of the configure step (in addition to the error, of course).

issue opened with some way to reproduce it.

> I think we should actually modernize the use of tuples (which will remove boost dependency here).

good idea, boost tuples are no really needed anymore w/ modern c++.

> Can you try https://github.com/supercollider/supercollider/tree/topic/cpp-structured-bindings ?

and that works, well done! closing this PR then in favor of #7119 

thanks for the help!

**Comment by dyfer** [comment]
Thanks @tharvik for reporting!
